class ExceptionObject {
	public void display(){
	System.out.println("test is displayed");
	}
	class ExceptionObject1 {
	public static void main(String args[]){
	Excetion c = null;
	try{
	c.display()
	}
	catch(EXception c){
	System.out.println(e);
	}
	}
	}
}